apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: chat-app
spec:
  selector:
    app: mongodb       # Must match the label in your deployment
  ports:
    - protocol: TCP
      port: 27017      # The port backend will connect to
      targetPort: 27017
  type: ClusterIP       # Default, accessible inside cluster
